In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
# Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Data Preprocessing

In [4]:
# Encode categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
# Onehot encode 'Geography
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [6]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [7]:
geo_encoded_df=pd.DataFrame(geo_encoder,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
## Combine one hot encoder columns with the original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
## Save the encoders and scaler
with open('output/label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('output/onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [12]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [14]:
X=data.drop('Exited',axis=1)
y=data['Exited']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [15]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [16]:
with open('output/scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## Model Training

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [19]:
(X_train.shape[1],)

(12,)

In [ ]:
# Build Our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ## HL1 Connected wwith input layer
    Dense(32,activation='relu'), ## HL2
    Dense(1,activation='sigmoid')  ## output layer
]

)

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2,945
Trainable params: 2,945
Non-trainable params: 0
_________________________________________________________________

In [22]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [ ]:
# compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [ ]:
# Set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [ ]:
# Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [ ]:
# Train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4122 - accuracy: 0.8202 - val_loss: 0.3481 - val_accuracy: 0.8585
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3561 - accuracy: 0.8496 - val_loss: 0.3609 - val_accuracy: 0.8560
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3442 - accuracy: 0.8580 - val_loss: 0.3561 - val_accuracy: 0.8560
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3441 - accuracy: 0.8602 - val_loss: 0.3449 - val_accuracy: 0.8585
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3385 - accuracy: 0.8602 - val_loss: 0.3425 - val_accuracy: 0.8575
Epoch 6/100
250/250 [==============================] - 1s 6ms/step - loss: 0.3358 - accuracy: 0.8606 - val_loss: 0.3474 - val_accuracy: 0.8590
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3352 - accuracy: 0.8602 - val_loss: 0.3398 - val_accuracy: 0.8590
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3317 - accuracy: 0.8615 - val_loss: 0.3389 - val_accuracy: 0.8570
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3295 - accuracy: 0.8624 - val_loss: 0.3503 - val_accuracy: 0.8595
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3278 - accuracy: 0.8664 - val_loss: 0.3401 - val_accuracy: 0.8615
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3274 - accuracy: 0.8629 - val_loss: 0.3424 - val_accuracy: 0.8600
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3241 - accuracy: 0.8654 - val_loss: 0.3402 - val_accuracy: 0.8640
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3234 - accuracy: 0.8659 - val_loss: 0.3485 - val_accuracy: 0.8530
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3210 - accuracy: 0.8680 - val_loss: 0.3493 - val_accuracy: 0.8590
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3216 - accuracy: 0.8680 - val_loss: 0.3540 - val_accuracy: 0.8600
Epoch 16/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3193 - accuracy: 0.8644 - val_loss: 0.3489 - val_accuracy: 0.8620
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3150 - accuracy: 0.8680 - val_loss: 0.3513 - val_accuracy: 0.8545
Epoch 18/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3138 - accuracy: 0.8689 - val_loss: 0.3703 - val_accuracy: 0.8590

In [27]:
model.save('output/model.h5')

In [34]:
# Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [ ]:
%tensorboard --logdir logs/fit

## Hyperparameter Tuning

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import pickle

In [35]:
## Define a function to create the model and try different parameters(KerasClassifier)

def create_model(neurons=32,layers=1):
    model=Sequential()
    model.add(Dense(neurons,activation='relu',input_shape=(X_train.shape[1],)))

    for _ in range(layers-1):
        model.add(Dense(neurons,activation='relu'))

    model.add(Dense(1,activation='sigmoid'))
    model.compile(optimizer='adam',loss="binary_crossentropy",metrics=['accuracy'])

    return model

In [36]:
## Create a Keras classifier
model=KerasClassifier(layers=1,neurons=32,build_fn=create_model,verbose=1)

In [37]:
# Define the grid search parameters
param_grid = {
    'neurons': [16, 32, 64, 128],
    'layers': [1, 2],
    'epochs': [50, 100]
}

In [38]:
# Perform grid search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3,verbose=1)
grid_result = grid.fit(X_train, y_train)

# Print the best parameters
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Fitting 3 folds for each of 16 candidates, totalling 48 fits

c:\Users\arpit\Desktop\ANN-churn-classifier\venv\lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7704
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4505 - accuracy: 0.8067
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4244 - accuracy: 0.8163
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4062 - accuracy: 0.8274
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3900 - accuracy: 0.8364
Epoch 6/100
250/250 [==============================] - 0s 953us/step - loss: 0.3777 - accuracy: 0.8438
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3692 - accuracy: 0.8476
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3626 - accuracy: 0.8510
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3582 - accuracy: 0.8536
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3540 - accuracy: 0.8556
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3515 - accuracy: 0.8583
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3493 - accuracy: 0.8579
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3473 - accuracy: 0.8577
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3455 - accuracy: 0.8593
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8586
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3430 - accuracy: 0.8585
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3419 - accuracy: 0.8611
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3411 - accuracy: 0.8600
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3405 - accuracy: 0.8600
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3397 - accuracy: 0.8596
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3391 - accuracy: 0.8591
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3386 - accuracy: 0.8586
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3384 - accuracy: 0.8587
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3377 - accuracy: 0.8610
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3376 - accuracy: 0.8610
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3371 - accuracy: 0.8620
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3370 - accuracy: 0.8611
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3362 - accuracy: 0.8601
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3362 - accuracy: 0.8614
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3360 - accuracy: 0.8596
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3355 - accuracy: 0.8612
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3353 - accuracy: 0.8599
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3345 - accuracy: 0.8621
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3348 - accuracy: 0.8610
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3346 - accuracy: 0.8609
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8619
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8624
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8612
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8622
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8626
Epoch 41/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3335 - accuracy: 0.8612
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3332 - accuracy: 0.8626
Epoch 43/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3329 - accuracy: 0.8626
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8626
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8633
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8609
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8620
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3323 - accuracy: 0.8625
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3322 - accuracy: 0.8618
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3320 - accuracy: 0.8636
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3321 - accuracy: 0.8627
Epoch 52/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8649
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3317 - accuracy: 0.8622
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3315 - accuracy: 0.8634
Epoch 55/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8620
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8616
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3312 - accuracy: 0.8620
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 0.8591
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3311 - accuracy: 0.8643
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8614
Epoch 61/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8620
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3303 - accuracy: 0.8619
Epoch 63/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8614
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8611
Epoch 65/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8637
Epoch 66/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8626
Epoch 67/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3301 - accuracy: 0.8640
Epoch 68/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3299 - accuracy: 0.8618
Epoch 69/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3299 - accuracy: 0.8629
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3295 - accuracy: 0.8629
Epoch 71/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8639
Epoch 72/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8618
Epoch 73/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3298 - accuracy: 0.8625
Epoch 74/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8636
Epoch 75/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3296 - accuracy: 0.8630
Epoch 76/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3295 - accuracy: 0.8634
Epoch 77/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8625
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8631
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8622
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8633
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8624
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3292 - accuracy: 0.8624
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8630
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8641
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8626
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8635
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8645
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3290 - accuracy: 0.8634
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8635
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8620
Epoch 91/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8612
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3287 - accuracy: 0.8631
Epoch 93/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8609
Epoch 94/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3288 - accuracy: 0.8641
Epoch 95/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3285 - accuracy: 0.8635
Epoch 96/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8634
Epoch 97/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3284 - accuracy: 0.8637
Epoch 98/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3284 - accuracy: 0.8620
Epoch 99/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3284 - accuracy: 0.8626
Epoch 100/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3286 - accuracy: 0.8639
Best: 0.857249 using {'epochs': 100, 'layers': 1, 'neurons': 16}

In [39]:
best_params = grid.best_params_
print(best_params)

{'epochs': 100, 'layers': 1, 'neurons': 16}

In [42]:
final_model = create_model(
    neurons=best_params['neurons'],
    layers=best_params['layers']
)

history=final_model.fit(
    X_train,
    y_train,
    epochs=best_params['epochs'],
    batch_size=32,
    verbose=1,
    callbacks=[tensorflow_callback,early_stopping_callback],
    validation_data=(X_test,y_test)
)

Epoch 1/100
250/250 [==============================] - 1s 4ms/step - loss: 0.5190 - accuracy: 0.7661 - val_loss: 0.4362 - val_accuracy: 0.8070
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4371 - accuracy: 0.8117 - val_loss: 0.4043 - val_accuracy: 0.8275
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4144 - accuracy: 0.8234 - val_loss: 0.3872 - val_accuracy: 0.8330
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3996 - accuracy: 0.8321 - val_loss: 0.3756 - val_accuracy: 0.8405
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3881 - accuracy: 0.8395 - val_loss: 0.3669 - val_accuracy: 0.8470
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3780 - accuracy: 0.8455 - val_loss: 0.3611 - val_accuracy: 0.8525
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3703 - accuracy: 0.8486 - val_loss: 0.3546 - val_accuracy: 0.8500
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3645 - accuracy: 0.8510 - val_loss: 0.3514 - val_accuracy: 0.8515
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3597 - accuracy: 0.8536 - val_loss: 0.3495 - val_accuracy: 0.8555
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3557 - accuracy: 0.8555 - val_loss: 0.3465 - val_accuracy: 0.8535
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3530 - accuracy: 0.8561 - val_loss: 0.3461 - val_accuracy: 0.8540
Epoch 12/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3508 - accuracy: 0.8574 - val_loss: 0.3457 - val_accuracy: 0.8560
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3491 - accuracy: 0.8568 - val_loss: 0.3443 - val_accuracy: 0.8545
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3475 - accuracy: 0.8571 - val_loss: 0.3444 - val_accuracy: 0.8565
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3466 - accuracy: 0.8565 - val_loss: 0.3438 - val_accuracy: 0.8575
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3458 - accuracy: 0.8570 - val_loss: 0.3442 - val_accuracy: 0.8590
Epoch 17/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3444 - accuracy: 0.8572 - val_loss: 0.3426 - val_accuracy: 0.8615
Epoch 18/100
250/250 [==============================] - 11s 46ms/step - loss: 0.3442 - accuracy: 0.8591 - val_loss: 0.3437 - val_accuracy: 0.8610
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8570 - val_loss: 0.3430 - val_accuracy: 0.8610
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3430 - accuracy: 0.8599 - val_loss: 0.3441 - val_accuracy: 0.8595
Epoch 21/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3426 - accuracy: 0.8586 - val_loss: 0.3435 - val_accuracy: 0.8620
Epoch 22/100
250/250 [==============================] - 3s 14ms/step - loss: 0.3422 - accuracy: 0.8581 - val_loss: 0.3439 - val_accuracy: 0.8600
Epoch 23/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3418 - accuracy: 0.8599 - val_loss: 0.3437 - val_accuracy: 0.8630
Epoch 24/100
250/250 [==============================] - 18s 71ms/step - loss: 0.3413 - accuracy: 0.8589 - val_loss: 0.3429 - val_accuracy: 0.8650
Epoch 25/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3411 - accuracy: 0.8584 - val_loss: 0.3435 - val_accuracy: 0.8625
Epoch 26/100
250/250 [==============================] - 6s 25ms/step - loss: 0.3407 - accuracy: 0.8596 - val_loss: 0.3440 - val_accuracy: 0.8600
Epoch 27/100
250/250 [==============================] - 6s 22ms/step - loss: 0.3404 - accuracy: 0.8584 - val_loss: 0.3437 - val_accuracy: 0.8615

In [43]:
final_model.save('output/final_model.h5')